# Generated by Django 6.0.6 on 2026-08-11 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSectorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='sectors.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo de usuário com setor',
                'verbose_name_plural': 'vínculos de usuários com setores',
                'ordering': ['user_id', '-is_primary', 'sector__name'],
                'permissions': [('manage_user_sector_membership', 'Pode gerenciar vínculos entre usuários e setores')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['user', 'active'], name='membership_user_active_idx'), models.Index(fields=['sector', 'active'], name='membership_sector_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'sector'), name='unique_user_sector_membership'), models.UniqueConstraint(condition=models.Q(('active', True), ('is_primary', True)), fields=('user',), name='unique_active_primary_sector_per_user'), models.CheckConstraint(condition=models.Q(('is_primary', False), ('active', True), _connector='OR'), name='primary_membership_must_be_active')],
            },
        ),
    ]
