# Generated by Django 6.0.6 on 2026-08-13 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0002_usersectormembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('acronym', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='sectors.organizationalunit')),
            ],
            options={
                'verbose_name': 'unidade organizacional',
                'verbose_name_plural': 'unidades organizacionais',
                'ordering': ['name', 'id'],
                'permissions': [('manage_organizational_unit', 'Pode gerenciar unidades organizacionais')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['parent', 'active'], name='org_unit_parent_active_idx')],
            },
        ),
    ]
