# Generated by Django 6.0.6 on 2026-08-13 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_organizationalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sectors', to='sectors.organizationalunit'),
        ),
    ]
