# Generated by Django 6.0.6 on 2026-08-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0004_sector_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'função organizacional',
                'verbose_name_plural': 'funções organizacionais',
                'ordering': ['name', 'id'],
                'permissions': [('manage_organizational_function', 'Pode gerenciar funções organizacionais')],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
    ]
