# Generated by Django 6.0.6 on 2026-08-13 17:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0005_organizationalfunction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersectormembership',
            name='ends_on',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='usersectormembership',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='sectors.organizationalfunction'),
        ),
        migrations.AddField(
            model_name='usersectormembership',
            name='starts_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='usersectormembership',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_memberships', to='sectors.organizationalunit'),
        ),
        migrations.AddConstraint(
            model_name='usersectormembership',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__isnull', True), ('ends_on__gte', models.F('starts_on')), _connector='OR'), name='membership_valid_date_range'),
        ),
    ]
