# Generated by Django 6.0.6 on 2026-08-11 19:12

import apps.processes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sectors', '0002_usersectormembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'tipo de processo',
                'verbose_name_plural': 'tipos de processo',
                'ordering': ['name', 'id'],
                'default_permissions': ('add', 'change', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AdministrativeProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=apps.processes.models.generate_process_number, editable=False, max_length=35, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('ARCHIVED', 'Arquivado')], db_index=True, default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('opened_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_processes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_processes', to=settings.AUTH_USER_MODEL)),
                ('current_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_processes', to='sectors.sector')),
                ('origin_sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='originated_processes', to='sectors.sector')),
                ('process_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.processtype')),
            ],
            options={
                'verbose_name': 'processo administrativo',
                'verbose_name_plural': 'processos administrativos',
                'ordering': ['-updated_at', 'id'],
                'permissions': [('open_administrativeprocess', 'Pode abrir processos'), ('forward_administrativeprocess', 'Pode encaminhar processos'), ('receive_administrativeprocess', 'Pode receber processos'), ('return_administrativeprocess', 'Pode devolver processos'), ('complete_administrativeprocess', 'Pode concluir processos'), ('reopen_administrativeprocess', 'Pode reabrir processos'), ('cancel_administrativeprocess', 'Pode cancelar processos'), ('archive_administrativeprocess', 'Pode arquivar processos')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['current_sector', 'status'], name='process_sector_status_idx'), models.Index(fields=['process_type', 'status'], name='process_type_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='process_version_gte_1'), models.CheckConstraint(condition=models.Q(('status', 'DRAFT'), ('current_sector__isnull', False), _connector='OR'), name='process_current_sector_outside_draft')],
            },
        ),
    ]
