# Generated by Django 6.0.6 on 2026-08-11 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        ('sectors', '0002_usersectormembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OPEN', 'Abertura'), ('FORWARD', 'Encaminhamento'), ('RECEIVE', 'Recebimento'), ('RETURN', 'Devolução'), ('COMPLETE', 'Conclusão'), ('REOPEN', 'Reabertura'), ('CANCEL', 'Cancelamento'), ('ARCHIVE', 'Arquivamento')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('status_before', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('ARCHIVED', 'Arquivado')], max_length=20)),
                ('status_after', models.CharField(choices=[('DRAFT', 'Rascunho'), ('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluído'), ('CANCELLED', 'Cancelado'), ('ARCHIVED', 'Arquivado')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_movements', to=settings.AUTH_USER_MODEL)),
                ('from_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_process_movements', to='sectors.sector')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='processes.administrativeprocess')),
                ('to_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_process_movements', to='sectors.sector')),
            ],
            options={
                'verbose_name': 'movimentação de processo',
                'verbose_name_plural': 'movimentações de processos',
                'ordering': ['created_at', 'id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['process', 'created_at'], name='movement_process_date_idx'), models.Index(fields=['from_sector', 'created_at'], name='movement_from_date_idx'), models.Index(fields=['to_sector', 'created_at'], name='movement_to_date_idx'), models.Index(fields=['action', 'created_at'], name='movement_action_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('action__in', ['RETURN', 'CANCEL', 'REOPEN']), ('note', ''), _negated=True), name='movement_required_note'), models.CheckConstraint(condition=models.Q(models.Q(('action', 'OPEN'), _negated=True), models.Q(('from_sector__isnull', True), ('to_sector__isnull', False)), _connector='OR'), name='movement_open_sector_coherence'), models.CheckConstraint(condition=models.Q(models.Q(('action__in', ['FORWARD', 'RETURN']), _negated=True), models.Q(('from_sector__isnull', False), ('to_sector__isnull', False), models.Q(('from_sector', models.F('to_sector')), _negated=True)), _connector='OR'), name='movement_transfer_sectors'), models.CheckConstraint(condition=models.Q(models.Q(('action', 'RECEIVE'), _negated=True), models.Q(('from_sector', models.F('to_sector')), ('from_sector__isnull', False)), _connector='OR'), name='movement_receive_sector')],
            },
        ),
    ]
