# Generated by Django 6.0.6 on 2026-08-11 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_processmovement'),
        ('sectors', '0002_usersectormembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='processmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ['COMPLETE', 'CANCEL', 'REOPEN', 'ARCHIVE']), _negated=True), models.Q(('from_sector', models.F('to_sector')), ('from_sector__isnull', False)), _connector='OR'), name='movement_state_action_sector'),
        ),
    ]
