# Generated by Django 6.0.6 on 2026-08-11 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_processmovement_movement_state_action_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PROCESS_CREATED', 'Processo criado'), ('DOCUMENT_CHANGED', 'Documento alterado'), ('DUE_DATE_CHANGED', 'Vencimento alterado'), ('PAYMENT_CHANGED', 'Pagamento alterado'), ('CORRECTION', 'Correção de histórico'), ('NOTE', 'Observação funcional'), ('SYSTEM', 'Evento de sistema')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_events', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='processes.administrativeprocess')),
            ],
            options={
                'verbose_name': 'evento funcional de processo',
                'verbose_name_plural': 'eventos funcionais de processos',
                'ordering': ['created_at', 'id'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['process', 'created_at'], name='event_process_date_idx'), models.Index(fields=['event_type', 'created_at'], name='event_type_date_idx')],
            },
        ),
    ]
