# Generated by Django 6.0.6 on 2026-08-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0005_administrativeworkflow_workflowversion_and_more'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('requires_manager', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_stages', to='sectors.organizationalfunction')),
                ('responsible_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_stages', to='sectors.sector')),
                ('workflow_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='processes.workflowversion')),
            ],
            options={
                'ordering': ['workflow_version_id', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('workflow_version', 'order'), name='unique_workflow_stage_order'), models.UniqueConstraint(condition=models.Q(('is_initial', True)), fields=('workflow_version',), name='unique_initial_stage_per_version'), models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('workflow_version',), name='unique_final_stage_per_version'), models.CheckConstraint(condition=models.Q(('order__gte', 1)), name='workflow_stage_order_gte_1'), models.CheckConstraint(condition=models.Q(('responsible_sector__isnull', False), ('responsible_function__isnull', False), _connector='OR'), name='workflow_stage_has_responsibility')],
            },
        ),
    ]
