# Generated by Django 6.0.6 on 2026-08-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0006_workflowstage'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('requires_note', models.BooleanField(default=False)),
                ('requires_attachment', models.BooleanField(default=False)),
                ('is_return', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_workflow_transitions', to='sectors.organizationalfunction')),
                ('authorized_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_workflow_transitions', to='sectors.sector')),
                ('destination_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='processes.workflowstage')),
                ('source_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='processes.workflowstage')),
            ],
            options={
                'ordering': ['source_stage_id', 'code', 'id'],
                'constraints': [models.UniqueConstraint(fields=('source_stage', 'code'), name='unique_transition_code_per_source'), models.CheckConstraint(condition=models.Q(('source_stage', models.F('destination_stage')), _negated=True), name='transition_changes_stage')],
            },
        ),
    ]
