# Generated by Django 6.0.6 on 2026-08-13 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0007_workflowtransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.workflowstage'),
        ),
        migrations.AddField(
            model_name='administrativeprocess',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='processes.workflowversion'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_types', to='processes.administrativeworkflow'),
        ),
    ]
