# Generated by Django 6.0.6 on 2026-08-13 18:09

import django.db.models.deletion
from django.db import migrations, models


def populate_stage_responsibility(apps, schema_editor):
    AdministrativeProcess = apps.get_model('processes', 'AdministrativeProcess')
    for process in AdministrativeProcess.objects.filter(current_stage__isnull=False).select_related('current_stage'):
        process.responsible_sector_id = process.current_stage.responsible_sector_id or process.origin_sector_id
        process.responsible_function_id = process.current_stage.responsible_function_id
        process.save(update_fields=['responsible_sector', 'responsible_function'])


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0008_administrativeprocess_current_stage_and_more'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativeprocess',
            name='responsible_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_processes', to='sectors.organizationalfunction'),
        ),
        migrations.AddField(
            model_name='administrativeprocess',
            name='responsible_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_processes', to='sectors.sector'),
        ),
        migrations.RunPython(populate_stage_responsibility, migrations.RunPython.noop),
    ]
