# Generated by Django 6.0.6 on 2026-08-13 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0009_administrativeprocess_responsible_function_and_more'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processmovement',
            name='from_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_assignment_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='from_responsible_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_responsibility_movements', to='sectors.organizationalfunction'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='from_responsible_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_responsibility_movements', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_process_movements', to='processes.workflowstage'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='to_assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_assignment_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='to_responsible_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_responsibility_movements', to='sectors.organizationalfunction'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='to_responsible_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_responsibility_movements', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='to_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_process_movements', to='processes.workflowstage'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='transition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_movements', to='processes.workflowtransition'),
        ),
        migrations.AddField(
            model_name='processmovement',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_movements', to='processes.workflowversion'),
        ),
    ]
