# Generated by Django 6.0.6 on 2026-08-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0010_processmovement_from_assignee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativeprocess',
            options={'default_permissions': ('add', 'change', 'view'), 'ordering': ['-updated_at', 'id'], 'permissions': [('open_administrativeprocess', 'Pode abrir processos'), ('forward_administrativeprocess', 'Pode encaminhar processos'), ('receive_administrativeprocess', 'Pode receber processos'), ('return_administrativeprocess', 'Pode devolver processos'), ('complete_administrativeprocess', 'Pode concluir processos'), ('reopen_administrativeprocess', 'Pode reabrir processos'), ('cancel_administrativeprocess', 'Pode cancelar processos'), ('archive_administrativeprocess', 'Pode arquivar processos'), ('assign_administrativeprocess', 'Pode atribuir responsáveis aos processos')], 'verbose_name': 'processo administrativo', 'verbose_name_plural': 'processos administrativos'},
        ),
        migrations.AlterField(
            model_name='processevent',
            name='event_type',
            field=models.CharField(choices=[('PROCESS_CREATED', 'Processo criado'), ('DOCUMENT_CHANGED', 'Documento alterado'), ('DUE_DATE_CHANGED', 'Vencimento alterado'), ('PAYMENT_CHANGED', 'Pagamento alterado'), ('CORRECTION', 'Correção de histórico'), ('NOTE', 'Observação funcional'), ('SYSTEM', 'Evento de sistema'), ('ASSIGNMENT_CHANGED', 'Responsável alterado')], max_length=32),
        ),
    ]
