# Generated by Django 6.0.6 on 2026-08-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0011_alter_administrativeprocess_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processmovement',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
