# Generated by Django 6.0.6 on 2026-08-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0012_processmovement_context_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtransition',
            name='required_document_role',
            field=models.CharField(blank=True, choices=[('GENERAL', 'Documento geral'), ('PAYMENT_RECEIPT', 'Comprovante de pagamento')], max_length=24),
        ),
    ]
