# Generated by Django 6.0.6 on 2026-08-13 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0013_workflowtransition_required_document_role'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processmovement',
            name='movement_transfer_sectors',
        ),
        migrations.AddConstraint(
            model_name='processmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('action__in', ['FORWARD', 'RETURN']), _negated=True), ('transition__isnull', False), models.Q(('from_sector__isnull', False), ('to_sector__isnull', False), models.Q(('from_sector', models.F('to_sector')), _negated=True)), _connector='OR'), name='movement_transfer_sectors'),
        ),
    ]
