# Generated by Django 6.0.6 on 2026-08-10 16:56

import apps.notifications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('SYSTEM', 'Sistema'), ('USER', 'Usuário'), ('DOCUMENT', 'Documento'), ('SECURITY', 'Segurança'), ('ADMIN', 'Administração')], default='SYSTEM', max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Informação'), ('SUCCESS', 'Sucesso'), ('WARNING', 'Atenção'), ('ERROR', 'Erro')], default='INFO', max_length=20)),
                ('action_url', models.CharField(blank=True, max_length=1000, validators=[apps.notifications.models.validate_action_url])),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', 'created_at'], name='notif_user_read_created'), models.Index(fields=['user', 'type', 'created_at'], name='notif_user_type_created')],
            },
        ),
    ]
