# Generated by Django 6.0.6 on 2026-08-11 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'Sistema'), ('USER', 'Usuário'), ('DOCUMENT', 'Documento'), ('SECURITY', 'Segurança'), ('ADMIN', 'Administração'), ('PAYMENT', 'Pagamento')], default='SYSTEM', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('deduplication_key', ''), _negated=True), fields=('user', 'deduplication_key'), name='unique_user_notification_dedupe'),
        ),
    ]
