import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize, forkJoin, of } from 'rxjs';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { OrganizationalUnit } from '../../models/sector.models';
import { SectorService } from '../../services/sector.service';

@Component({selector:'app-unit-form',imports:[ReactiveFormsModule,RouterLink,PageHeader],template:`
  <app-page-header [title]="id?'Editar unidade':'Nova unidade'" description="Informe a identificação e posição hierárquica."><a class="btn btn-outline-secondary" routerLink="/administracao/estrutura/unidades">Voltar</a></app-page-header>
  @if(!loading()){<form class="card border-0 shadow-sm" [formGroup]="form" (ngSubmit)="submit()" novalidate><div class="card-body row g-3 p-4"><div class="col-md-8"><label class="form-label" for="unit-name">Nome</label><input id="unit-name" class="form-control" formControlName="name" [class.is-invalid]="invalid('name')"><div class="invalid-feedback">Informe o nome.</div></div><div class="col-md-4"><label class="form-label" for="unit-acronym">Sigla</label><input id="unit-acronym" class="form-control" maxlength="30" formControlName="acronym" [class.is-invalid]="invalid('acronym')"><div class="invalid-feedback">Informe a sigla.</div></div><div class="col-12"><label class="form-label" for="unit-description">Descrição</label><textarea id="unit-description" class="form-control" rows="3" formControlName="description"></textarea></div><div class="col-md-8"><label class="form-label" for="unit-parent">Unidade superior</label><select id="unit-parent" class="form-select" formControlName="parent"><option value="">Nenhuma (raiz)</option>@for(item of parents();track item.id){<option [value]="item.id">{{item.name}} ({{item.acronym}})</option>}</select></div><div class="col-md-4 d-flex align-items-end"><div class="form-check form-switch mb-2"><input id="unit-active" class="form-check-input" type="checkbox" formControlName="active"><label for="unit-active" class="form-check-label">Unidade ativa</label></div></div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary" [disabled]="saving()">{{saving()?'Salvando…':'Salvar unidade'}}</button></div></form>}@if(error()){<div class="alert alert-danger mt-3">{{error()}}</div>}
`})
export class UnitForm{
  private readonly fb=inject(FormBuilder);private readonly api=inject(SectorService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly id=Number(this.route.snapshot.paramMap.get('id'))||0;readonly loading=signal(true);readonly saving=signal(false);readonly error=signal('');readonly parents=signal<OrganizationalUnit[]>([]);readonly form=this.fb.nonNullable.group({name:['',Validators.required],acronym:['',Validators.required],description:[''],parent:[''],active:[true]});
  constructor(){forkJoin({units:this.api.units('true'),item:this.id?this.api.getUnit(this.id):of(null)}).subscribe({next:({units,item})=>{this.parents.set(units.results.filter(unit=>unit.id!==this.id));if(item)this.form.patchValue({name:item.name,acronym:item.acronym,description:item.description,parent:item.parent?String(item.parent):'',active:item.active});this.loading.set(false);},error:()=>{this.error.set('Não foi possível carregar a unidade.');this.loading.set(false);}});}
  invalid(name:string){const c=this.form.get(name);return Boolean(c?.invalid&&(c.dirty||c.touched));}
  submit(){this.form.markAllAsTouched();if(this.form.invalid||this.saving())return;const v=this.form.getRawValue(),payload={name:v.name.trim(),acronym:v.acronym.trim(),description:v.description.trim(),parent:v.parent?Number(v.parent):null,active:v.active};this.saving.set(true);this.error.set('');(this.id?this.api.updateUnit(this.id,payload):this.api.createUnit(payload)).pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>this.router.navigateByUrl('/administracao/estrutura/unidades'),error:r=>this.error.set(this.first(r.error)||'Não foi possível salvar a unidade.')});}
  private first(error:unknown){if(!error||typeof error!=='object')return'';const v=Object.values(error as Record<string,unknown>)[0];return Array.isArray(v)?String(v[0]):String(v||'');}
}
