# Generated by Django 6.0.6 on 2026-08-10 14:39

import apps.core.models
from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    apps.get_model('core', 'SystemSettings').objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Base Admin', max_length=120)),
                ('system_short_name', models.CharField(default='BA', max_length=12)),
                ('system_description', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(default='0.1.0', max_length=30)),
                ('logo', models.FileField(blank=True, upload_to=apps.core.models.logo_upload_path, validators=[apps.core.models.validate_logo])),
                ('primary_color', models.CharField(default='#4a4ab8', max_length=7)),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=64)),
                ('language_code', models.CharField(default='pt-br', max_length=16)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do sistema',
                'verbose_name_plural': 'configurações do sistema',
            },
        ),
        migrations.RunPython(create_default_settings, migrations.RunPython.noop),
    ]
