# Generated by Django 6.0.6 on 2026-08-11 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'permissions': [('generate_reports', 'Pode gerar relatórios')], 'verbose_name': 'configuração do sistema', 'verbose_name_plural': 'configurações do sistema'},
        ),
    ]
