import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { UserPayload, UserSectorMembership } from '../../../../core/models/application.models';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { OrganizationalFunction, OrganizationalUnit, SectorTreeNode } from '../../../sectors/models/sector.models';
import { SectorService } from '../../../sectors/services/sector.service';
import { UserService } from '../services/user.service';

@Component({
  selector: 'app-user-form', imports: [ReactiveFormsModule, RouterLink, PageHeader],
  template: `
    <app-page-header [title]="title" [description]="description"><a class="btn btn-outline-secondary" routerLink="/administracao/usuarios">Voltar</a></app-page-header>
    <form class="card border-0 shadow-sm" [formGroup]="form" (ngSubmit)="submit()" novalidate><div class="card-body p-3 p-md-4"><div class="row g-3">
      <div class="col-12 col-md-6"><label class="form-label" for="firstName">Nome</label><input id="firstName" class="form-control" formControlName="firstName" [class.is-invalid]="invalid('firstName')"><div class="invalid-feedback">Informe o nome.</div></div>
      <div class="col-12 col-md-6"><label class="form-label" for="lastName">Sobrenome</label><input id="lastName" class="form-control" formControlName="lastName"></div>
      <div class="col-12 col-md-6"><label class="form-label" for="email">E-mail</label><input id="email" class="form-control" type="email" formControlName="email" [class.is-invalid]="invalid('email')"><div class="invalid-feedback">Informe um e-mail válido.</div></div>
      <div class="col-12 col-md-6"><label class="form-label" for="username">Usuário</label><input id="username" class="form-control" formControlName="username" [class.is-invalid]="invalid('username')"><div class="invalid-feedback">Use pelo menos 3 caracteres.</div></div>
      @if (!id) { <div class="col-12 col-md-6"><label class="form-label" for="password">Senha inicial</label><input id="password" class="form-control" type="password" formControlName="password" [class.is-invalid]="invalid('password')"><div class="invalid-feedback">Use pelo menos 8 caracteres.</div></div> }
      <div class="col-12 col-md-6"><label class="form-label" for="group">Perfil/Grupo</label><select id="group" class="form-select" formControlName="group"><option>Administrador</option><option>Usuário</option></select></div>
      <div class="col-12"><div class="form-check form-switch"><input id="active" class="form-check-input" type="checkbox" formControlName="active"><label class="form-check-label" for="active">Usuário ativo</label></div></div>
    </div></div>
    @if (!viewMode) { <div class="card-footer bg-white d-flex justify-content-end gap-2 p-3"><a class="btn btn-light" routerLink="/administracao/usuarios">Cancelar</a><button class="btn btn-primary" type="submit" [disabled]="saving()">{{ saving() ? 'Salvando…' : 'Salvar usuário' }}</button></div> }
    </form>
    @if (id) { <section class="card border-0 shadow-sm mt-4"><div class="card-header bg-white py-3"><strong>Vínculos organizacionais</strong></div><div class="card-body"><div class="row g-3 align-items-end mb-4"><div class="col-12 col-md-3"><label class="form-label" for="membership-unit">Unidade</label><select id="membership-unit" class="form-select" [formControl]="membershipForm.controls.unit"><option value="">Selecione</option>@for (unit of units(); track unit.id) { <option [value]="unit.id">{{ unit.name }}</option> }</select></div><div class="col-12 col-md-3"><label class="form-label" for="membership-sector">Setor</label><select id="membership-sector" class="form-select" [formControl]="membershipForm.controls.sector"><option value="">Selecione</option>@for (sector of sectors(); track sector.id) { <option [value]="sector.id">{{ sector.name }}{{ sector.unit_acronym ? ' — ' + sector.unit_acronym : '' }}</option> }</select></div><div class="col-12 col-md-3"><label class="form-label" for="membership-function">Função</label><select id="membership-function" class="form-select" [formControl]="membershipForm.controls.function"><option value="">Selecione</option>@for (item of functions(); track item.id) { <option [value]="item.id">{{ item.name }}</option> }</select></div><div class="col-6 col-md-1"><div class="form-check"><input id="membership-primary" class="form-check-input" type="checkbox" [formControl]="membershipForm.controls.primary"><label class="form-check-label" for="membership-primary">Principal</label></div></div><div class="col-6 col-md-1"><div class="form-check"><input id="membership-manager" class="form-check-input" type="checkbox" [formControl]="membershipForm.controls.manager"><label class="form-check-label" for="membership-manager">Responsável</label></div></div><div class="col-12 col-md-1"><button class="btn btn-outline-primary w-100" type="button" [disabled]="viewMode || membershipForm.invalid" (click)="addMembership()">Adicionar</button></div></div>@for (membership of memberships(); track membership.id) { <div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-2 border-top py-3"><div><strong>{{ membership.sector_name }}</strong>@if (membership.sector_code) { <code class="ms-2">{{ membership.sector_code }}</code> }<small class="d-block text-body-secondary">{{ membership.unit_name || 'Unidade legada' }} · {{ membership.function_name || 'Função legada' }} · {{ membership.is_primary ? 'Principal' : 'Adicional' }}{{ membership.is_manager ? ' · Responsável' : '' }}</small></div>@if (!viewMode) { <button class="btn btn-sm btn-outline-secondary" type="button" (click)="deactivateMembership(membership)">Inativar</button> }</div> } @empty { <p class="text-body-secondary mb-0">Nenhum vínculo vigente.</p> }</div></section> }
    @if (error()) { <div class="alert alert-danger mt-3" role="alert">Não foi possível salvar o usuário. Revise os dados informados.</div> }
  `
})
export class UserForm {
  private readonly fb = inject(FormBuilder); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private readonly api = inject(UserService); private readonly sectorsApi = inject(SectorService);
  readonly viewMode = this.route.snapshot.data['mode'] === 'view'; readonly id = Number(this.route.snapshot.paramMap.get('id')) || 0; readonly saving = signal(false); readonly error = signal(false);
  readonly title = this.id ? (this.viewMode ? 'Detalhes do usuário' : 'Editar usuário') : 'Novo usuário'; readonly description = this.viewMode ? 'Consulte os dados e acessos do usuário.' : 'Preencha os dados cadastrais e defina o perfil de acesso.';
  readonly form = this.fb.nonNullable.group({ firstName: ['', Validators.required], lastName: [''], email: ['', [Validators.required, Validators.email]], username: ['', [Validators.required, Validators.minLength(3)]], password: ['', this.id ? [] : [Validators.required, Validators.minLength(8)]], group: ['Usuário', Validators.required], active: [true] });
  readonly memberships = signal<UserSectorMembership[]>([]); readonly units = signal<OrganizationalUnit[]>([]); readonly functions = signal<OrganizationalFunction[]>([]); readonly sectors = signal<{id:number;name:string;unit_acronym:string|null}[]>([]); readonly membershipForm = this.fb.nonNullable.group({ unit: ['', Validators.required], sector: ['', Validators.required], function: ['', Validators.required], primary: [false], manager: [false] });
  constructor() { if (this.id) { this.loadMemberships(); this.sectorsApi.units().subscribe(page => this.units.set(page.results)); this.sectorsApi.functions().subscribe(page => this.functions.set(page.results)); this.sectorsApi.tree('true').subscribe(tree => this.sectors.set(this.flattenSectors(tree))); this.api.get(this.id).subscribe(user => { this.form.patchValue({ firstName: user.first_name, lastName: user.last_name, email: user.email, username: user.username, group: user.groups[0] || 'Usuário', active: user.is_active }); if (this.viewMode) { this.form.disable(); this.membershipForm.disable(); } }); } }
  invalid(control: string) { const field = this.form.get(control); return Boolean(field?.invalid && (field.dirty || field.touched)); }
  submit() { this.form.markAllAsTouched(); if (this.form.invalid || this.saving()) return; const value = this.form.getRawValue(); const payload: UserPayload = { first_name: value.firstName, last_name: value.lastName, email: value.email, username: value.username, is_active: value.active, group_names: [value.group], ...(this.id ? {} : { password: value.password }) }; this.saving.set(true); this.error.set(false); const request = this.id ? this.api.update(this.id, payload) : this.api.create(payload); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => this.router.navigateByUrl('/administracao/usuarios'), error: () => this.error.set(true) }); }
  addMembership() { if (this.membershipForm.invalid) return; const value=this.membershipForm.getRawValue(); this.api.addMembership({user:this.id,unit:Number(value.unit),sector:Number(value.sector),function:Number(value.function),active:true,is_primary:value.primary,is_manager:value.manager}).subscribe({next:()=>{this.membershipForm.reset({unit:'',sector:'',function:'',primary:false,manager:false});this.loadMemberships();},error:()=>this.error.set(true)}); }
  deactivateMembership(item: UserSectorMembership) { this.api.updateMembership(item.id,{active:false,is_primary:false}).subscribe({next:()=>this.loadMemberships(),error:()=>this.error.set(true)}); }
  private loadMemberships() { this.api.memberships(this.id).subscribe(response=>this.memberships.set(response.results)); }
  private flattenSectors(nodes: SectorTreeNode[]): {id:number;name:string;unit_acronym:string|null}[] { return nodes.flatMap(node=>[{id:node.id,name:node.name,unit_acronym:node.unit_acronym},...this.flattenSectors(node.children)]); }
}
