import { DatePipe, JsonPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { PageHeader } from '../../../../../shared/components/page-header/page-header';
import { AuditLog } from '../../models/audit.models';
import { AuditService } from '../../services/audit.service';

@Component({
  selector: 'app-audit-detail', imports: [DatePipe, JsonPipe, RouterLink, PageHeader],
  template: `<app-page-header title="Detalhes da auditoria" description="Registro funcional somente para consulta."><a class="btn btn-outline-secondary" routerLink="/administracao/auditoria">Voltar</a></app-page-header>@if (error()) { <div class="alert alert-danger">Registro não encontrado.</div> } @if (log(); as item) { <section class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><dl class="row mb-0"><dt class="col-sm-3">Data/Hora</dt><dd class="col-sm-9">{{ item.created_at | date:'medium' }}</dd><dt class="col-sm-3">Usuário</dt><dd class="col-sm-9">{{ item.user_name }}</dd><dt class="col-sm-3">Ação</dt><dd class="col-sm-9"><span class="badge text-bg-light border">{{ item.action_display }}</span></dd><dt class="col-sm-3">Entidade</dt><dd class="col-sm-9"><code>{{ item.entity_type || '—' }} {{ item.entity_id || '' }}</code></dd><dt class="col-sm-3">Método/Rota</dt><dd class="col-sm-9"><code>{{ item.request_method || '—' }} {{ item.request_path || '' }}</code></dd><dt class="col-sm-3">IP</dt><dd class="col-sm-9">{{ item.ip_address || '—' }}</dd><dt class="col-sm-3">User agent</dt><dd class="col-sm-9 text-break">{{ item.user_agent || '—' }}</dd><dt class="col-sm-3">Descrição</dt><dd class="col-sm-9 mb-0">{{ item.description }}</dd></dl></div></section><div class="row g-4"><div class="col-12 col-xl-6"><section class="card border-0 shadow-sm h-100"><div class="card-header bg-white">Valores anteriores</div><div class="card-body"><pre class="audit-json mb-0">{{ item.old_values | json }}</pre></div></section></div><div class="col-12 col-xl-6"><section class="card border-0 shadow-sm h-100"><div class="card-header bg-white">Valores novos</div><div class="card-body"><pre class="audit-json mb-0">{{ item.new_values | json }}</pre></div></section></div></div> }`,
  styles: [`.audit-json{padding:1rem;border-radius:.5rem;background:#f7f8fa;color:#343741;white-space:pre-wrap;overflow-wrap:anywhere;font-size:.8rem}`]
})
export class AuditDetail { private readonly api=inject(AuditService); private readonly route=inject(ActivatedRoute); readonly log=signal<AuditLog|null>(null); readonly error=signal(false); constructor(){this.api.get(Number(this.route.snapshot.paramMap.get('id'))).subscribe({next:value=>this.log.set(value),error:()=>this.error.set(true)});} }
