import { CurrencyPipe, DecimalPipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { forkJoin } from 'rxjs';
import { AuthService } from '../../../../core/auth/auth.service';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { PaymentGroupReport, PaymentReportSummary, ProcessReportSummary, ReportFilters, SectorTimeReport } from '../../models/report.models';
import { ReportService } from '../../services/report.service';

@Component({selector:'app-report-dashboard',imports:[CurrencyPipe,DecimalPipe,ReactiveFormsModule,PageHeader],template:`
<app-page-header title="Relatórios" description="Visão gerencial por processos, setores, fornecedores e pagamentos."></app-page-header>
<form class="card border-0 shadow-sm mb-4" [formGroup]="form" (ngSubmit)="apply()"><div class="card-body"><div class="row g-3">
<div class="col-md-3"><label class="form-label" for="report-from">Data inicial</label><input id="report-from" class="form-control" type="date" formControlName="date_from"></div>
<div class="col-md-3"><label class="form-label" for="report-to">Data final</label><input id="report-to" class="form-control" type="date" formControlName="date_to"></div>
<div class="col-md-3"><label class="form-label" for="report-sector">Setor</label><input id="report-sector" class="form-control" inputmode="numeric" formControlName="sector" placeholder="ID do setor"></div>
<div class="col-md-3"><label class="form-label" for="report-type">Tipo de processo</label><input id="report-type" class="form-control" inputmode="numeric" formControlName="type" placeholder="ID do tipo"></div>
<div class="col-md-3"><label class="form-label" for="report-responsible">Responsável</label><input id="report-responsible" class="form-control" inputmode="numeric" formControlName="responsible" placeholder="ID do usuário"></div>
<div class="col-md-3"><label class="form-label" for="report-process-status">Estado do processo</label><select id="report-process-status" class="form-select" formControlName="process_status"><option value="">Todos</option><option value="DRAFT">Rascunho</option><option value="OPEN">Aberto</option><option value="IN_PROGRESS">Em andamento</option><option value="COMPLETED">Concluído</option><option value="CANCELLED">Cancelado</option><option value="ARCHIVED">Arquivado</option></select></div>
@if(canViewFinancial){<div class="col-md-3"><label class="form-label" for="report-payment-status">Estado do pagamento</label><select id="report-payment-status" class="form-select" formControlName="payment_status"><option value="">Todos</option><option value="PENDING">Pendente</option><option value="SCHEDULED">Agendado</option><option value="PAID">Pago</option><option value="CANCELLED">Cancelado</option></select></div><div class="col-md-3"><label class="form-label" for="report-supplier">Fornecedor</label><input id="report-supplier" class="form-control" inputmode="numeric" formControlName="supplier" placeholder="ID do fornecedor"></div><div class="col-md-3"><label class="form-label" for="report-min">Valor mínimo</label><input id="report-min" class="form-control" type="number" min="0" step="0.01" formControlName="min_amount"></div><div class="col-md-3"><label class="form-label" for="report-max">Valor máximo</label><input id="report-max" class="form-control" type="number" min="0" step="0.01" formControlName="max_amount"></div><div class="col-md-3"><label class="form-label" for="report-purpose">Finalidade</label><input id="report-purpose" class="form-control" formControlName="purpose"></div>}
</div></div><div class="card-footer bg-white d-flex gap-2"><button class="btn btn-primary" type="submit" [disabled]="loading()">Aplicar filtros</button><button class="btn btn-light" type="button" (click)="clear()">Limpar</button></div></form>
@if(error()){<div class="alert alert-danger">Não foi possível carregar os relatórios.</div>}
@if(processes();as data){<section class="mb-4"><h2 class="h5">Processos</h2><div class="row g-3"><div class="col-md-4"><article class="card card-body border-0 shadow-sm"><small>Total no período</small><strong class="fs-3">{{data.total}}</strong></article></div><div class="col-md-8"><div class="card border-0 shadow-sm table-responsive"><table class="table mb-0"><thead><tr><th>Estado</th><th class="text-end">Quantidade</th></tr></thead><tbody>@for(item of data.by_status;track item.status){<tr><td>{{item.status}}</td><td class="text-end">{{item.count}}</td></tr>}@empty{<tr><td colspan="2" class="text-center text-body-secondary py-4">Nenhum processo encontrado.</td></tr>}</tbody></table></div></div></div></section>}
<section class="mb-4"><h2 class="h5">Tempo por setor</h2><div class="card border-0 shadow-sm table-responsive"><table class="table mb-0"><thead><tr><th>Setor</th><th class="text-end">Tempo médio</th><th class="text-end">Períodos</th></tr></thead><tbody>@for(item of times();track item.sector){<tr><td>{{item.sector_name}}</td><td class="text-end">{{item.average_hours|number:'1.1-2'}} h</td><td class="text-end">{{item.movements}}</td></tr>}@empty{<tr><td colspan="3" class="text-center text-body-secondary py-4">Sem movimentações para os filtros selecionados.</td></tr>}</tbody></table></div></section>
@if(canViewFinancial&&payments();as data){<section><h2 class="h5">Pagamentos</h2><div class="row g-3 mb-3"><div class="col-md-4"><article class="card card-body border-0 shadow-sm"><small>Quantidade</small><strong class="fs-3">{{data.count}}</strong></article></div><div class="col-md-4"><article class="card card-body border-0 shadow-sm"><small>Total</small><strong class="fs-3">{{+data.total|currency:'BRL'}}</strong></article></div><div class="col-md-4"><article class="card card-body border-0 shadow-sm"><small>Média</small><strong class="fs-3">{{+data.average|currency:'BRL'}}</strong></article></div></div><div class="row g-3"><div class="col-lg-6"><div class="card border-0 shadow-sm table-responsive"><table class="table mb-0"><thead><tr><th>Setor</th><th>Qtd.</th><th class="text-end">Total</th></tr></thead><tbody>@for(item of paymentSectors();track item.sector){<tr><td>{{item.name}}</td><td>{{item.count}}</td><td class="text-end">{{+item.total|currency:'BRL'}}</td></tr>}@empty{<tr><td colspan="3" class="text-center text-body-secondary py-4">Nenhum pagamento.</td></tr>}</tbody></table></div></div><div class="col-lg-6"><div class="card border-0 shadow-sm table-responsive"><table class="table mb-0"><thead><tr><th>Fornecedor</th><th>Qtd.</th><th class="text-end">Total</th></tr></thead><tbody>@for(item of paymentSuppliers();track item.supplier){<tr><td>{{item.name}}</td><td>{{item.count}}</td><td class="text-end">{{+item.total|currency:'BRL'}}</td></tr>}@empty{<tr><td colspan="3" class="text-center text-body-secondary py-4">Nenhum pagamento.</td></tr>}</tbody></table></div></div></div></section>}
`})
export class ReportDashboard{
 private readonly api=inject(ReportService);private readonly fb=inject(FormBuilder);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly auth=inject(AuthService);
 readonly canViewFinancial=this.auth.can('payments.view_financial_data')&&this.auth.can('payments.view_payment');readonly loading=signal(false);readonly error=signal(false);readonly processes=signal<ProcessReportSummary|null>(null);readonly times=signal<SectorTimeReport[]>([]);readonly payments=signal<PaymentReportSummary|null>(null);readonly paymentSectors=signal<PaymentGroupReport[]>([]);readonly paymentSuppliers=signal<PaymentGroupReport[]>([]);
 readonly form=this.fb.nonNullable.group({date_from:'',date_to:'',sector:'',type:'',responsible:'',process_status:'',payment_status:'',supplier:'',min_amount:'',max_amount:'',purpose:''});
 constructor(){this.form.patchValue(this.route.snapshot.queryParams);this.load();}
 apply(){const values=this.form.getRawValue();this.router.navigate([],{relativeTo:this.route,queryParams:values,replaceUrl:true});this.load();}clear(){this.form.reset();this.apply();}
 private load(){this.loading.set(true);this.error.set(false);const filters=this.form.getRawValue() as ReportFilters;forkJoin({processes:this.api.processSummary(filters),times:this.api.timeBySector(filters)}).subscribe({next:data=>{this.processes.set(data.processes);this.times.set(data.times);this.loading.set(false)},error:()=>{this.error.set(true);this.loading.set(false)}});if(this.canViewFinancial)forkJoin({summary:this.api.paymentSummary(filters),sectors:this.api.paymentsBySector(filters),suppliers:this.api.paymentsBySupplier(filters)}).subscribe({next:data=>{this.payments.set(data.summary);this.paymentSectors.set(data.sectors);this.paymentSuppliers.set(data.suppliers)},error:()=>this.error.set(true)});}
}
