# Generated by Django 6.0.6 on 2026-08-10 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('ACTIVATE', 'Ativação'), ('DEACTIVATE', 'Desativação'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Falha de login'), ('PASSWORD_CHANGED', 'Senha alterada'), ('DOCUMENT_VIEW', 'Documento visualizado'), ('DOCUMENT_DOWNLOAD', 'Documento baixado'), ('SETTINGS_CHANGED', 'Configurações alteradas')], db_index=True, max_length=32)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
