# Generated by Django 6.0.6 on 2026-08-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Criação'), ('UPDATE', 'Atualização'), ('ACTIVATE', 'Ativação'), ('DEACTIVATE', 'Desativação'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Falha de login'), ('PASSWORD_CHANGED', 'Senha alterada'), ('DOCUMENT_VIEW', 'Documento visualizado'), ('DOCUMENT_DOWNLOAD', 'Documento baixado'), ('SETTINGS_CHANGED', 'Configurações alteradas'), ('PROCESS_WORKFLOW', 'Tramitação de processo'), ('PROCESS_EVENT', 'Evento funcional de processo'), ('PAYMENT_WORKFLOW', 'Fluxo de pagamento'), ('FILE_LIFECYCLE', 'Ciclo de vida de arquivo')], db_index=True, max_length=32),
        ),
    ]
