import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { concatMap, finalize, forkJoin, from, of, switchMap, toArray } from 'rxjs';

import { AuthService } from '../../../../core/auth/auth.service';
import { UserSectorMembershipSummary } from '../../../../core/models/application.models';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { DocumentCategory } from '../../../documents/models/document.models';
import { DocumentService } from '../../../documents/services/document.service';
import { ProcessPayload, ProcessType } from '../../models/process.models';
import { ProcessService } from '../../services/process.service';

@Component({
  selector: 'app-process-form', imports: [ReactiveFormsModule, RouterLink, PageHeader],
  template: `
    <app-page-header [title]="id ? 'Editar processo' : 'Novo processo'" description="Informe os dados básicos do processo administrativo."><a class="btn btn-outline-secondary" [routerLink]="id ? ['/processos', id] : ['/processos']">Voltar</a></app-page-header>
    @if (loading()) { <div class="card border-0 shadow-sm"><div class="card-body p-5 text-center text-body-secondary">Carregando…</div></div> } @else {
      @if (notEditable()) { <div class="alert alert-warning" role="alert">Somente processos em rascunho podem ser editados.</div> }
      @if (!id && !memberships().length) { <div class="alert alert-warning" role="alert">Você precisa de um vínculo organizacional ativo e vigente para criar um processo.</div> }
      <form class="card border-0 shadow-sm" [formGroup]="form" (ngSubmit)="submit()" novalidate><div class="card-body row g-3 p-4">
        <div class="col-12 col-lg-8"><label class="form-label" for="process-title">Título</label><input id="process-title" class="form-control" maxlength="200" formControlName="title" [class.is-invalid]="invalid('title')"><div class="invalid-feedback">Informe o título do processo.</div></div>
        <div class="col-12 col-lg-4"><label class="form-label" for="process-type">Classificação do processo</label><select id="process-type" class="form-select" formControlName="process_type" [class.is-invalid]="invalid('process_type')"><option value="">Selecione</option>@for (item of types(); track item.id) { <option [value]="item.id">{{ item.name }}</option> }</select><div class="invalid-feedback">Selecione uma classificação.</div><div class="form-text">Indica a finalidade do processo; não define seu fluxo nem o tipo dos documentos.</div></div>
        <div class="col-12"><label class="form-label" for="process-description">Descrição</label><textarea id="process-description" class="form-control" rows="5" formControlName="description"></textarea></div>
        <div class="col-12"><label class="form-label" [attr.for]="memberships().length > 1 && !id ? 'process-origin' : null">Origem organizacional</label>
          @if (id) { <div class="form-control bg-body-tertiary">{{ existingOrigin() }}</div><div class="form-text">A origem não pode ser alterada após a criação.</div> }
          @else if (memberships().length > 1) { <select id="process-origin" class="form-select" formControlName="origin_membership" [class.is-invalid]="invalid('origin_membership')"><option value="">Selecione um vínculo</option>@for (item of memberships(); track item.id) { <option [value]="item.id">{{ membershipLabel(item) }}</option> }</select><div class="invalid-feedback">Selecione um dos seus vínculos autorizados.</div> }
          @else if (memberships().length === 1) { <div class="form-control bg-body-tertiary">{{ membershipLabel(memberships()[0]) }}</div><div class="form-text">Origem determinada pelo seu vínculo vigente.</div> }
          @else { <div class="form-control bg-body-tertiary text-body-secondary">Nenhuma origem disponível</div> }
          @if (!id && selectedMembership(); as origin) { <dl class="row small bg-body-tertiary rounded p-3 mt-2 mb-0"><dt class="col-sm-3">Unidade</dt><dd class="col-sm-9">{{ origin.unit_name || 'Não informada' }}{{ origin.unit_acronym ? ' (' + origin.unit_acronym + ')' : '' }}</dd><dt class="col-sm-3">Setor</dt><dd class="col-sm-9">{{ origin.sector_name }}{{ origin.sector_code ? ' (' + origin.sector_code + ')' : '' }}</dd><dt class="col-sm-3">Função</dt><dd class="col-sm-9 mb-0">{{ origin.function_name || 'Não informada' }}</dd></dl> }
        </div>
        @if (!id && canAttach()) {
          <div class="col-12"><hr class="my-2"><h2 class="h5 mb-1">Documentos iniciais</h2><p class="text-body-secondary small mb-2">Opcional. Os arquivos serão incluídos no dossiê após a criação do processo.</p></div>
          <div class="col-12 col-md-5"><label class="form-label" for="process-document-category">Categoria dos documentos</label><select id="process-document-category" class="form-select" formControlName="document_category" [class.is-invalid]="invalid('document_category')"><option value="">Selecione</option>@for (category of categories(); track category.id) { <option [value]="category.id">{{ category.name }}</option> }</select><div class="invalid-feedback">Selecione a categoria dos arquivos.</div></div>
          <div class="col-12 col-md-7"><label class="form-label" for="process-files">Arquivos</label><input id="process-files" class="form-control" type="file" multiple accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.png,.jpg,.jpeg" (change)="selectFiles($event)" aria-describedby="process-files-help"><div id="process-files-help" class="form-text">PDF, Office, texto ou imagem; até 10 MB por arquivo.</div></div>
          @if (selectedNames()) { <div class="col-12"><small class="text-body-secondary">Selecionados: {{ selectedNames() }}</small></div> }
          @if (fileError()) { <div class="col-12"><div class="alert alert-danger mb-0" role="alert">{{ fileError() }}</div></div> }
        }
      </div><div class="card-footer bg-white d-flex justify-content-end gap-2 p-3"><a class="btn btn-light" [routerLink]="id ? ['/processos', id] : ['/processos']">Cancelar</a><button class="btn btn-primary" type="submit" [disabled]="saving() || notEditable() || (!id && !memberships().length)">{{ saving() ? 'Salvando…' : 'Salvar processo' }}</button></div></form>
    }
    @if (error()) { <div class="alert alert-danger mt-3" role="alert">{{ error() }}</div> }
  `
})
export class ProcessForm {
  private readonly fb = inject(FormBuilder); private readonly api = inject(ProcessService); private readonly documentApi = inject(DocumentService); private readonly auth = inject(AuthService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router); private files: File[] = [];
  readonly id = Number(this.route.snapshot.paramMap.get('id')) || 0; readonly loading = signal(true); readonly saving = signal(false); readonly error = signal(''); readonly fileError = signal(''); readonly selectedNames = signal(''); readonly notEditable = signal(false); readonly existingOrigin = signal('');
  readonly types = signal<ProcessType[]>([]); readonly memberships = signal<UserSectorMembershipSummary[]>([]); readonly categories = signal<DocumentCategory[]>([]);
  readonly form = this.fb.nonNullable.group({ title: ['', Validators.required], description: [''], process_type: ['', Validators.required], origin_membership: [''], document_category: [''] });
  constructor() { const item$ = this.id ? this.api.get(this.id) : of(null); const categories$ = !this.id && this.canAttach() ? this.documentApi.categories() : of({ results: [] }); forkJoin({ types: this.api.types(), item: item$, categories: categories$ }).subscribe({ next: ({ types, item, categories }) => { if (item && !types.some(type => type.id === item.process_type)) types.push({ id: item.process_type, name: `${item.process_type_name} (inativo)`, code: '', description: '' }); this.types.set(types); this.categories.set(categories.results.filter(category => category.active)); this.memberships.set(this.auth.user()?.sector_memberships || []); if (!this.id && this.memberships().length > 1) this.form.controls.origin_membership.addValidators(Validators.required); if (item) { this.notEditable.set(item.status !== 'DRAFT'); this.existingOrigin.set(item.origin_sector_name); this.form.patchValue({ title: item.title, description: item.description || '', process_type: String(item.process_type) }); } this.loading.set(false); }, error: response => { this.error.set(this.errorMessage(response)); this.loading.set(false); } }); }
  invalid(name: string) { const control = this.form.get(name); return Boolean(control?.invalid && (control.dirty || control.touched)); }
  membershipLabel(item: UserSectorMembershipSummary) { return `${item.unit_name || 'Unidade não informada'} · ${item.sector_name}${item.function_name ? ' · ' + item.function_name : ''}${item.is_primary ? ' · Principal' : ''}`; }
  selectedMembership() { if (this.memberships().length === 1) return this.memberships()[0]; const id = Number(this.form.controls.origin_membership.value); return this.memberships().find(item => item.id === id); }
  canAttach() { return this.auth.can('documents.add_document') && this.auth.can('documents.add_attachment'); }
  selectFiles(event: Event) { this.files = Array.from((event.target as HTMLInputElement).files || []); this.selectedNames.set(this.files.map(file => file.name).join(', ')); if (!this.files.length) this.form.controls.document_category.setErrors(null); this.validateFiles(); }
  submit() { this.form.markAllAsTouched(); if (this.files.length && !this.form.controls.document_category.value) this.form.controls.document_category.setErrors({ required: true }); if (!this.validateFiles() || this.form.invalid || this.saving() || this.notEditable()) return; const value = this.form.getRawValue(); const membership = this.memberships().length === 1 ? this.memberships()[0].id : Number(value.origin_membership) || undefined; const payload: ProcessPayload = { title: value.title.trim(), description: value.description.trim(), process_type: Number(value.process_type), ...(!this.id && membership ? { origin_membership: membership } : {}) }; this.saving.set(true); this.error.set(''); let createdProcessId = 0; const request = this.id ? this.api.update(this.id, payload) : this.api.create(payload).pipe(switchMap(process => { createdProcessId = process.id; if (!this.files.length) return of(process); return from(this.files).pipe(concatMap(file => this.api.createDocument(process.id, { title: file.name, description: '', category: Number(value.document_category), role: 'GENERAL' }).pipe(switchMap(document => this.api.addAttachment(document.id, file)))), toArray(), switchMap(() => of(process))); })); request.pipe(finalize(() => this.saving.set(false))).subscribe({ next: item => this.router.navigate(['/processos', item.id]), error: response => { if (createdProcessId) { this.router.navigate(['/processos', createdProcessId], { queryParams: { upload: 'incomplete' } }); return; } this.error.set(this.firstError(response.error) || this.errorMessage(response)); } }); }
  private validateFiles() { const invalid = this.files.find(file => file.size > 10 * 1024 * 1024 || !/\.(pdf|docx?|xlsx?|txt|png|jpe?g)$/i.test(file.name)); this.fileError.set(invalid ? `O arquivo ${invalid.name} possui extensão ou tamanho inválido.` : ''); return !invalid; }
  private errorMessage(response: { status?: number }) { return response?.status === 403 ? 'Você não possui permissão ou vínculo vigente para esta operação.' : response?.status === 404 ? 'Processo não encontrado ou fora do seu escopo.' : response?.status === 409 ? 'O processo foi alterado por outro usuário. Recarregue antes de salvar.' : 'Não foi possível carregar ou salvar o processo.'; }
  private firstError(error: unknown): string { if (!error || typeof error !== 'object') return ''; const value = Object.values(error as Record<string, unknown>)[0]; return Array.isArray(value) ? String(value[0]) : String(value || ''); }
}
