import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { SettingsService } from '../../services/settings.service';

@Component({
  selector: 'app-settings-form', imports: [ReactiveFormsModule, PageHeader],
  template: `
    <app-page-header title="Configurações do sistema" description="Personalize informações públicas e o comportamento geral do ambiente." />
    @if (loading()) { <div class="card border-0 shadow-sm"><div class="card-body p-5 text-center text-body-secondary">Carregando…</div></div> }
    @else { <form [formGroup]="form" (ngSubmit)="submit()" novalidate>
      <section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3">Geral</div><div class="card-body row g-3"><div class="col-12 col-md-8"><label class="form-label" for="name">Nome do sistema</label><input id="name" class="form-control" formControlName="systemName"></div><div class="col-12 col-md-4"><label class="form-label" for="shortName">Nome curto</label><input id="shortName" class="form-control" maxlength="12" formControlName="shortName"></div><div class="col-12"><label class="form-label" for="description">Descrição</label><textarea id="description" class="form-control" rows="2" formControlName="description"></textarea></div><div class="col-12 col-md-4"><label class="form-label" for="version">Versão</label><input id="version" class="form-control" formControlName="version"></div></div></section>
      <section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3">Identidade visual</div><div class="card-body row g-3"><div class="col-12 col-md-8"><label class="form-label" for="logo">Logo</label><input id="logo" class="form-control" type="file" accept=".png,.jpg,.jpeg,.webp" (change)="selectLogo($event)"><div class="form-text">PNG, JPG ou WEBP, até 2 MB.</div></div><div class="col-12 col-md-4"><label class="form-label" for="color">Cor principal</label><div class="input-group"><input id="color-picker" class="form-control form-control-color" type="color" formControlName="primaryColor"><input id="color" class="form-control" formControlName="primaryColor"></div></div></div></section>
      <section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3">Localização</div><div class="card-body row g-3"><div class="col-12 col-md-6"><label class="form-label" for="timezone">Timezone</label><input id="timezone" class="form-control" formControlName="timezone"></div><div class="col-12 col-md-6"><label class="form-label" for="language">Idioma</label><input id="language" class="form-control" formControlName="languageCode"></div></div></section>
      <section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white py-3">Suporte</div><div class="card-body row g-3"><div class="col-12 col-md-6"><label class="form-label" for="email">E-mail</label><input id="email" class="form-control" type="email" formControlName="supportEmail"></div><div class="col-12 col-md-6"><label class="form-label" for="url">URL</label><input id="url" class="form-control" type="url" formControlName="supportUrl"></div></div></section>
      <section class="card border-0 shadow-sm"><div class="card-header bg-white py-3">Sistema</div><div class="card-body"><div class="form-check form-switch"><input id="maintenance" class="form-check-input" type="checkbox" formControlName="maintenanceMode"><label class="form-check-label" for="maintenance">Modo manutenção</label></div><small class="text-body-secondary">Usuários comuns serão direcionados para a página de manutenção. Administradores continuam com acesso.</small></div><div class="card-footer bg-white d-flex justify-content-end"><button class="btn btn-primary" type="submit" [disabled]="saving()">{{ saving() ? 'Salvando…' : 'Salvar configurações' }}</button></div></section>
    </form> }
    @if (success()) { <div class="alert alert-success mt-3">Configurações atualizadas.</div> } @if (error()) { <div class="alert alert-danger mt-3">Não foi possível salvar. Revise os campos.</div> }
  `
})
export class SettingsForm {
  private readonly fb = inject(FormBuilder); private readonly api = inject(SettingsService); private logo: File | null = null;
  readonly loading = signal(true); readonly saving = signal(false); readonly success = signal(false); readonly error = signal(false);
  readonly form = this.fb.nonNullable.group({ systemName: ['', Validators.required], shortName: ['', Validators.required], description: [''], version: ['', Validators.required], primaryColor: ['#4a4ab8', [Validators.required, Validators.pattern(/^#[0-9a-fA-F]{6}$/)]], timezone: ['', Validators.required], languageCode: ['', Validators.required], supportEmail: ['', Validators.email], supportUrl: ['', Validators.pattern(/^$|^https?:\/\/.+/i)], maintenanceMode: [false] });
  constructor() { this.api.getAdmin().subscribe({ next: value => { this.form.patchValue({ systemName: value.system_name, shortName: value.system_short_name, description: value.system_description, version: value.version, primaryColor: value.primary_color, timezone: value.timezone, languageCode: value.language_code, supportEmail: value.support_email, supportUrl: value.support_url, maintenanceMode: value.maintenance_mode }); this.loading.set(false); }, error: () => { this.loading.set(false); this.error.set(true); } }); }
  selectLogo(event: Event) { const file = (event.target as HTMLInputElement).files?.[0] ?? null; this.logo = file && file.size <= 2 * 1024 * 1024 ? file : null; if (file && !this.logo) this.error.set(true); }
  submit() { this.form.markAllAsTouched(); if (this.form.invalid || this.saving()) return; const value = this.form.getRawValue(); const payload = new FormData(); payload.set('system_name', value.systemName); payload.set('system_short_name', value.shortName); payload.set('system_description', value.description); payload.set('version', value.version); payload.set('primary_color', value.primaryColor); payload.set('timezone', value.timezone); payload.set('language_code', value.languageCode); payload.set('support_email', value.supportEmail); payload.set('support_url', value.supportUrl); payload.set('maintenance_mode', String(value.maintenanceMode)); if (this.logo) payload.set('logo', this.logo); this.saving.set(true); this.success.set(false); this.error.set(false); this.api.update(payload).pipe(finalize(() => this.saving.set(false))).subscribe({ next: () => this.success.set(true), error: () => this.error.set(true) }); }
}
