import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { PageHeader } from '../../../shared/components/page-header/page-header';
import { SectorService } from '../../sectors/services/sector.service';
import { OrganizationalFunction, Sector } from '../../sectors/models/sector.models';
import { Workflow, WorkflowStage, WorkflowTransition } from './workflow.models';
import { WorkflowService } from './workflow.service';

@Component({selector:'app-workflow-admin',imports:[ReactiveFormsModule,PageHeader],template:`
<app-page-header title="Fluxos administrativos" description="Configure versões, etapas ordenadas, responsabilidades e transições sem informar IDs internos." />
@if(error()){<div class="alert alert-danger">{{error()}}</div>}
<div class="row g-4"><div class="col-xl-4"><section class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Fluxos</strong></div><div class="list-group list-group-flush">@for(item of workflows();track item.id){<button type="button" class="list-group-item list-group-item-action" [class.active]="selected()?.id===item.id" (click)="select(item)"><strong>{{item.name}}</strong><small class="d-block">{{item.code}} · v{{item.version}} · {{item.active?'ativo':'inativo'}}</small></button>}</div><form class="card-body border-top" [formGroup]="workflowForm" (ngSubmit)="createWorkflow()"><h3 class="h6">Novo fluxo</h3><input class="form-control mb-2" placeholder="Nome" formControlName="name"><input class="form-control mb-2" placeholder="Código" formControlName="code"><textarea class="form-control mb-2" placeholder="Descrição" formControlName="description"></textarea><button class="btn btn-primary w-100" [disabled]="workflowForm.invalid">Criar fluxo</button></form></section></div>
<div class="col-xl-8">@if(selected();as flow){<section class="card border-0 shadow-sm mb-4"><div class="card-header bg-white d-flex justify-content-between"><strong>Etapas de {{flow.name}}</strong><button class="btn btn-sm btn-outline-secondary" (click)="toggleWorkflow(flow)">{{flow.active?'Inativar':'Ativar'}}</button></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Ordem</th><th>Etapa</th><th>Responsabilidade</th><th>Tipo</th></tr></thead><tbody>@for(item of stages();track item.id){<tr><td>{{item.order}}</td><td>{{item.name}}</td><td>{{item.sector_name||'Qualquer setor'}}{{item.function_name?' · '+item.function_name:''}}</td><td>{{item.is_initial?'Inicial':item.is_final?'Final':'Intermediária'}}</td></tr>}</tbody></table></div><form class="card-body border-top row g-2" [formGroup]="stageForm" (ngSubmit)="createStage()"><div class="col-md-2"><input type="number" min="1" class="form-control" formControlName="order" aria-label="Ordem"></div><div class="col-md-5"><input class="form-control" placeholder="Nome da etapa" formControlName="name"></div><div class="col-md-5"><select class="form-select" formControlName="responsible_sector"><option value="">Setor (opcional)</option>@for(item of sectors();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></div><div class="col-md-6"><select class="form-select" formControlName="responsible_function"><option value="">Função (opcional)</option>@for(item of functions();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></div><div class="col-md-6 d-flex gap-3 align-items-center"><label><input type="checkbox" formControlName="is_initial"> Inicial</label><label><input type="checkbox" formControlName="is_final"> Final</label><label><input type="checkbox" formControlName="requires_manager"> Exige gestor</label></div><div class="col-12 text-end"><button class="btn btn-primary" [disabled]="stageForm.invalid">Adicionar etapa</button></div></form></section>
<section class="card border-0 shadow-sm"><div class="card-header bg-white"><strong>Transições</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Ação</th><th>Origem → destino</th><th>Requisitos</th><th></th></tr></thead><tbody>@for(item of transitions();track item.id){<tr><td>{{item.name}}</td><td>{{item.source_name}} → {{item.destination_name}}</td><td>{{item.requires_note?'observação ':''}}{{item.requires_attachment?'anexo ':''}}{{item.is_return?'devolução':''}}</td><td><button class="btn btn-sm btn-outline-secondary" (click)="toggleTransition(item)">{{item.active?'Inativar':'Ativar'}}</button></td></tr>}</tbody></table></div><form class="card-body border-top row g-2" [formGroup]="transitionForm" (ngSubmit)="createTransition()"><div class="col-md-6"><select class="form-select" formControlName="source_stage"><option value="">Etapa de origem</option>@for(item of stages();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></div><div class="col-md-6"><select class="form-select" formControlName="destination_stage"><option value="">Etapa de destino</option>@for(item of stages();track item.id){<option [value]="item.id">{{item.name}}</option>}</select></div><div class="col-md-4"><input class="form-control" placeholder="Código" formControlName="code"></div><div class="col-md-8"><input class="form-control" placeholder="Nome da ação" formControlName="name"></div><div class="col-12 d-flex gap-3"><label><input type="checkbox" formControlName="requires_note"> Exige observação</label><label><input type="checkbox" formControlName="requires_attachment"> Exige anexo</label><label><input type="checkbox" formControlName="is_return"> Devolução</label></div><div class="col-12 text-end"><button class="btn btn-primary" [disabled]="transitionForm.invalid||stages().length<2">Adicionar transição</button></div></form></section>}</div></div>`})
export class WorkflowAdmin{
 private fb=inject(FormBuilder);private api=inject(WorkflowService);private sectorsApi=inject(SectorService);
 workflows=signal<Workflow[]>([]);selected=signal<Workflow|null>(null);stages=signal<WorkflowStage[]>([]);transitions=signal<WorkflowTransition[]>([]);sectors=signal<Sector[]>([]);functions=signal<OrganizationalFunction[]>([]);error=signal('');
 workflowForm=this.fb.nonNullable.group({name:['',Validators.required],code:['',Validators.required],description:[''],active:[true]});
 stageForm=this.fb.nonNullable.group({order:[1,[Validators.required,Validators.min(1)]],name:['',Validators.required],responsible_sector:[''],responsible_function:[''],is_initial:[false],is_final:[false],requires_manager:[false]});
 transitionForm=this.fb.nonNullable.group({source_stage:['',Validators.required],destination_stage:['',Validators.required],code:['',Validators.required],name:['',Validators.required],requires_note:[false],requires_attachment:[false],is_return:[false],active:[true]});
 constructor(){this.load();forkJoin({sectors:this.sectorsApi.list('','true'),functions:this.sectorsApi.functions('true')}).subscribe(({sectors,functions})=>{this.sectors.set(sectors.results);this.functions.set(functions.results)});}
 load(){this.api.workflows().subscribe({next:r=>{this.workflows.set(r.results);if(!this.selected()&&r.results.length)this.select(r.results[0])},error:()=>this.error.set('Não foi possível carregar os fluxos.')});}
 select(flow:Workflow){this.selected.set(flow);forkJoin({stages:this.api.stages(flow.id),transitions:this.api.transitions(flow.id)}).subscribe(({stages,transitions})=>{this.stages.set(stages.results);this.transitions.set(transitions.results)});}
 createWorkflow(){this.api.createWorkflow(this.workflowForm.getRawValue()).subscribe({next:item=>{this.workflowForm.reset({name:'',code:'',description:'',active:true});this.load();this.select(item)},error:e=>this.fail(e)});}
 createStage(){const flow=this.selected();if(!flow)return;const v=this.stageForm.getRawValue();this.api.createStage({...v,workflow_version:flow.current_version,responsible_sector:v.responsible_sector?Number(v.responsible_sector):null,responsible_function:v.responsible_function?Number(v.responsible_function):null}).subscribe({next:()=>{this.stageForm.reset({order:this.stages().length+1,name:'',responsible_sector:'',responsible_function:'',is_initial:false,is_final:false,requires_manager:false});this.select(flow)},error:e=>this.fail(e)});}
 createTransition(){const flow=this.selected();if(!flow)return;const v=this.transitionForm.getRawValue();this.api.createTransition({...v,source_stage:Number(v.source_stage),destination_stage:Number(v.destination_stage),authorized_sector:null,authorized_function:null}).subscribe({next:()=>{this.transitionForm.reset({source_stage:'',destination_stage:'',code:'',name:'',requires_note:false,requires_attachment:false,is_return:false,active:true});this.select(flow)},error:e=>this.fail(e)});}
 toggleWorkflow(item:Workflow){if(!confirm(`${item.active?'Inativar':'Ativar'} este fluxo?`))return;this.api.updateWorkflow(item.id,{active:!item.active}).subscribe({next:updated=>{this.load();this.select(updated)},error:e=>this.fail(e)});}
 toggleTransition(item:WorkflowTransition){this.api.updateTransition(item.id,{active:!item.active}).subscribe({next:()=>this.select(this.selected()!),error:e=>this.fail(e)});}
 private fail(e:any){this.error.set(e?.error?JSON.stringify(e.error):'Não foi possível salvar a configuração.');}
}
