import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { StatusBadge } from '../../../../shared/components/status-badge/status-badge';
import { OrganizationalFunction } from '../../models/sector.models';
import { SectorService } from '../../services/sector.service';

@Component({selector:'app-function-list',imports:[FormsModule,RouterLink,PageHeader,StatusBadge],template:`
  <app-page-header title="Funções" description="Gerencie as funções organizacionais sem alterar grupos de acesso."><a class="btn btn-primary" routerLink="/administracao/estrutura/funcoes/nova">+ Nova função</a></app-page-header><section class="card border-0 shadow-sm"><div class="card-body border-bottom"><div class="row g-3"><div class="col-md-8"><label class="form-label" for="function-search">Buscar</label><input id="function-search" class="form-control" [(ngModel)]="search" placeholder="Nome ou código"></div><div class="col-md-4"><label class="form-label" for="function-status">Status</label><select id="function-status" class="form-select" [(ngModel)]="status" (change)="load()"><option value="">Todos</option><option value="true">Ativas</option><option value="false">Inativas</option></select></div></div></div>@if(error()){<div class="alert alert-danger m-3">{{error()}}</div>}<div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Função</th><th>Descrição</th><th>Status</th><th class="text-end">Ações</th></tr></thead><tbody>@for(item of filtered();track item.id){<tr><td><strong>{{item.name}}</strong><code class="ms-2">{{item.code}}</code></td><td>{{item.description||'Sem descrição'}}</td><td><app-status-badge [active]="item.active" /></td><td class="text-end"><a class="btn btn-sm btn-outline-primary me-1" [routerLink]="['/administracao/estrutura/funcoes',item.id,'editar']">Editar</a><button class="btn btn-sm btn-outline-secondary" (click)="toggle(item)">{{item.active?'Inativar':'Ativar'}}</button></td></tr>}@empty{@if(!loading()){<tr><td colspan="4" class="text-center text-body-secondary py-5">Nenhuma função encontrada.</td></tr>}}</tbody></table></div></section>
`})
export class FunctionList{private readonly api=inject(SectorService);readonly items=signal<OrganizationalFunction[]>([]);readonly loading=signal(true);readonly error=signal('');search='';status='';readonly filtered=()=>this.items().filter(item=>!this.search||`${item.name} ${item.code}`.toLowerCase().includes(this.search.toLowerCase()));constructor(){this.load();}load(){this.loading.set(true);this.api.functions(this.status).subscribe({next:p=>{this.items.set(p.results);this.loading.set(false);},error:()=>{this.error.set('Não foi possível carregar as funções.');this.loading.set(false);}});}toggle(item:OrganizationalFunction){this.api.updateFunction(item.id,{active:!item.active}).subscribe({next:()=>this.load(),error:()=>this.error.set('Não foi possível alterar a função.')});}}
