import { DatePipe } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { PageHeader } from '../../../../../shared/components/page-header/page-header';
import { AuditLog } from '../../models/audit.models';
import { AuditService } from '../../services/audit.service';

@Component({
  selector: 'app-audit-list', imports: [DatePipe, FormsModule, RouterLink, PageHeader],
  template: `<app-page-header title="Auditoria" description="Consulte ações funcionais importantes executadas no sistema." />
  <section class="card border-0 shadow-sm"><div class="card-body border-bottom"><div class="row g-3"><div class="col-12 col-lg-4"><label class="form-label" for="audit-search">Buscar</label><input id="audit-search" class="form-control" type="search" [(ngModel)]="search" placeholder="Descrição, entidade ou usuário" (keyup.enter)="apply()"></div><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="action">Ação</label><select id="action" class="form-select" [(ngModel)]="action" (change)="apply()"><option value="">Todas</option>@for (item of actions; track item) { <option [value]="item">{{ item }}</option> }</select></div><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="entity">Entidade</label><input id="entity" class="form-control" [(ngModel)]="entity" placeholder="documents.Document" (keyup.enter)="apply()"></div><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="dateFrom">Data inicial</label><input id="dateFrom" class="form-control" type="date" [(ngModel)]="dateFrom" (change)="apply()"></div><div class="col-12 col-sm-6 col-lg-2"><label class="form-label" for="dateTo">Data final</label><input id="dateTo" class="form-control" type="date" [(ngModel)]="dateTo" (change)="apply()"></div></div></div>
  @if (error()) { <div class="alert alert-danger m-3">Não foi possível carregar a auditoria.</div> }
  <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Data/Hora</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>Descrição</th><th>IP</th><th class="text-end">Ações</th></tr></thead><tbody>@for (log of logs(); track log.id) { <tr><td class="text-nowrap">{{ log.created_at | date:'short' }}</td><td>{{ log.user_name }}</td><td><span class="badge text-bg-light border">{{ log.action_display }}</span></td><td><code>{{ log.entity_type || '—' }}</code><small class="d-block text-body-secondary">{{ log.entity_id || '' }}</small></td><td>{{ log.description }}</td><td>{{ log.ip_address || '—' }}</td><td class="text-end"><a class="btn btn-sm btn-outline-primary" [routerLink]="['/administracao/auditoria', log.id]">Detalhes</a></td></tr> } @empty { @if (!loading()) { <tr><td colspan="7" class="text-center text-body-secondary py-5">Nenhum registro encontrado.</td></tr> } }</tbody></table></div>
  <div class="card-footer bg-white d-flex justify-content-between align-items-center"><small class="text-body-secondary">{{ loading() ? 'Carregando…' : 'Exibindo ' + logs().length + ' de ' + count() + ' registros' }}</small><nav><ul class="pagination pagination-sm mb-0"><li class="page-item" [class.disabled]="page() === 1"><button class="page-link" type="button" (click)="go(page()-1)">Anterior</button></li><li class="page-item active"><span class="page-link">{{ page() }}</span></li><li class="page-item" [class.disabled]="!next()"><button class="page-link" type="button" (click)="go(page()+1)">Próxima</button></li></ul></nav></div></section>`
})
export class AuditList {
  private readonly api = inject(AuditService); readonly logs = signal<AuditLog[]>([]); readonly count = signal(0); readonly next = signal<string | null>(null); readonly page = signal(1); readonly loading = signal(true); readonly error = signal(false);
  readonly actions = ['CREATE','UPDATE','ACTIVATE','DEACTIVATE','LOGIN','LOGOUT','LOGIN_FAILED','PASSWORD_CHANGED','DOCUMENT_VIEW','DOCUMENT_DOWNLOAD','SETTINGS_CHANGED']; search=''; action=''; entity=''; dateFrom=''; dateTo='';
  constructor() { this.load(); } apply() { this.page.set(1); this.load(); } go(page:number) { if (page < 1 || (page > this.page() && !this.next())) return; this.page.set(page); this.load(); }
  private load() { this.loading.set(true); this.error.set(false); this.api.list({ search:this.search, action:this.action, entity:this.entity, dateFrom:this.dateFrom, dateTo:this.dateTo, page:this.page(), ordering:'-created_at' }).subscribe({ next: result => { this.logs.set(result.results); this.count.set(result.count); this.next.set(result.next); this.loading.set(false); }, error: () => { this.error.set(true); this.loading.set(false); } }); }
}
