# Generated by Django 6.0.6 on 2026-08-11 19:58

import apps.documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_legacy_sources_to_attachments(apps, schema_editor):
    Document = apps.get_model('documents', 'Document')
    Attachment = apps.get_model('documents', 'Attachment')
    for document in Document.objects.iterator():
        values = {
            'document_id': document.pk,
            'created_by_id': document.created_by_id,
            'original_file_name': document.original_file_name,
            'active': document.active,
        }
        if document.file:
            values['file'] = document.file.name
        elif document.external_url:
            values['external_url'] = document.external_url
        else:
            continue
        Attachment.objects.create(**values)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('processes', '0004_processevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='processes.administrativeprocess'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=apps.documents.models.attachment_upload_path, validators=[apps.documents.models.validate_document_file])),
                ('original_file_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=1000, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attachments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='documents.document')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ['created_at', 'id'],
                'permissions': [('manage_attachment', 'Pode gerenciar anexos')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['document', 'active', 'created_at'], name='attachment_doc_active_idx')],
            },
        ),
        migrations.RunPython(copy_legacy_sources_to_attachments, migrations.RunPython.noop),
    ]
