# Generated by Django 6.0.6 on 2026-08-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_process_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='role',
            field=models.CharField(choices=[('GENERAL', 'Documento geral'), ('PAYMENT_RECEIPT', 'Comprovante de pagamento')], db_index=True, default='GENERAL', max_length=24),
        ),
    ]
