# Generated by Django 6.0.6 on 2026-08-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_role'),
        ('processes', '0013_workflowtransition_required_document_role'),
        ('sectors', '0006_usersectormembership_ends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='context_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='attachment',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_attachments', to='sectors.organizationalfunction'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_attachments', to='sectors.sector'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='processes.workflowstage'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='processes.workflowversion'),
        ),
    ]
