# Generated by Django 6.0.6 on 2026-08-11 20:19

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_document_process_attachment'),
        ('processes', '0004_processevent'),
        ('sectors', '0002_usersectormembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('tax_id', models.CharField(max_length=14, unique=True, validators=[apps.payments.models.validate_tax_id])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=30)),
                ('bank_account', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['name', 'id'],
                'default_permissions': ('add', 'change', 'view'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('bank_account', ''), ('bank_branch', ''), ('bank_name', '')), models.Q(models.Q(('bank_name', ''), _negated=True), models.Q(('bank_branch', ''), _negated=True), models.Q(('bank_account', ''), _negated=True)), _connector='OR'), name='supplier_bank_data_complete')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SCHEDULED', 'Agendado'), ('PAID', 'Pago'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='documents.document')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='processes.administrativeprocess')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sectors.sector')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.supplier')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['due_date', 'id'],
                'permissions': [('view_financial_data', 'Pode visualizar dados financeiros'), ('confirm_payment', 'Pode confirmar pagamentos')],
                'default_permissions': ('add', 'change', 'view'),
                'indexes': [models.Index(fields=['sector', 'status', 'due_date'], name='payment_sector_status_due_idx'), models.Index(fields=['supplier', 'status', 'due_date'], name='pay_supplier_status_due_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_nonnegative'), models.CheckConstraint(condition=models.Q(('paid_amount__isnull', True), ('paid_amount__gte', 0), _connector='OR'), name='payment_paid_amount_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), models.Q(('paid_amount__isnull', False), ('paid_at__isnull', False), ('paid_by__isnull', False)), _connector='OR'), name='payment_paid_fields_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'SCHEDULED'), _negated=True), ('scheduled_at__isnull', False), _connector='OR'), name='payment_scheduled_at_required'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), ('cancelled_at__isnull', False), _connector='OR'), name='payment_cancelled_at_required'), models.CheckConstraint(condition=models.Q(('status', 'PAID'), models.Q(('paid_amount__isnull', True), ('paid_at__isnull', True), ('paid_by__isnull', True)), _connector='OR'), name='payment_paid_fields_only_when_paid'), models.CheckConstraint(condition=models.Q(('status', 'CANCELLED'), ('cancelled_at__isnull', True), _connector='OR'), name='payment_cancelled_at_only_cancelled')],
            },
        ),
    ]
