# Generated by Django 6.0.6 on 2026-08-11 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_process_attachment'),
        ('payments', '0001_initial'),
        ('processes', '0004_processevent'),
        ('sectors', '0002_usersectormembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'default_permissions': ('add', 'change', 'view'), 'ordering': ['due_date', 'id'], 'permissions': [('view_financial_data', 'Pode visualizar dados financeiros'), ('confirm_payment', 'Pode confirmar pagamentos'), ('schedule_payment', 'Pode agendar pagamentos'), ('cancel_payment', 'Pode cancelar pagamentos')], 'verbose_name': 'pagamento', 'verbose_name_plural': 'pagamentos'},
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_paid_fields_required',
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='payment_paid_fields_only_when_paid',
        ),
        migrations.AddField(
            model_name='payment',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('BANK_TRANSFER', 'Transferência bancária'), ('BOLETO', 'Boleto'), ('CARD', 'Cartão'), ('CASH', 'Dinheiro'), ('OTHER', 'Outro')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), models.Q(('paid_amount__isnull', False), ('paid_at__isnull', False), ('paid_by__isnull', False), models.Q(('payment_method', ''), _negated=True)), _connector='OR'), name='payment_paid_fields_required'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CANCELLED'), _negated=True), models.Q(('cancellation_reason', ''), _negated=True), _connector='OR'), name='payment_cancel_reason_required'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'PAID'), models.Q(('paid_amount__isnull', True), ('paid_at__isnull', True), ('paid_by__isnull', True), ('payment_method', '')), _connector='OR'), name='payment_paid_fields_only_when_paid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'CANCELLED'), ('cancellation_reason', ''), _connector='OR'), name='payment_cancel_reason_only_cancelled'),
        ),
    ]
