# Generated by Django 6.0.6 on 2026-08-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_role'),
        ('payments', '0002_alter_payment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='documents.attachment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='payments.payment')),
            ],
            options={
                'verbose_name': 'comprovante de pagamento',
                'verbose_name_plural': 'comprovantes de pagamento',
                'ordering': ['created_at', 'id'],
                'permissions': [('manage_payment_receipt', 'Pode gerenciar comprovantes de pagamento')],
                'default_permissions': ('view',),
            },
        ),
    ]
