# Generated by Django 6.0.6 on 2026-08-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentreceipt'),
        ('processes', '0013_workflowtransition_required_document_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='processes.workflowstage'),
        ),
        migrations.AddField(
            model_name='payment',
            name='workflow_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='processes.workflowversion'),
        ),
    ]
