import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { PageHeader } from '../../../../shared/components/page-header/page-header';
import { SectorService } from '../../services/sector.service';

@Component({selector:'app-function-form',imports:[ReactiveFormsModule,RouterLink,PageHeader],template:`
  <app-page-header [title]="id?'Editar função':'Nova função'" description="Funções representam postos organizacionais, não grupos de acesso."><a class="btn btn-outline-secondary" routerLink="/administracao/estrutura/funcoes">Voltar</a></app-page-header><form class="card border-0 shadow-sm" [formGroup]="form" (ngSubmit)="submit()"><div class="card-body row g-3 p-4"><div class="col-md-8"><label class="form-label" for="function-name">Nome</label><input id="function-name" class="form-control" formControlName="name"></div><div class="col-md-4"><label class="form-label" for="function-code">Código</label><input id="function-code" class="form-control" maxlength="30" formControlName="code"></div><div class="col-12"><label class="form-label" for="function-description">Descrição</label><textarea id="function-description" class="form-control" rows="3" formControlName="description"></textarea></div><div class="col-12"><div class="form-check form-switch"><input id="function-active" class="form-check-input" type="checkbox" formControlName="active"><label class="form-check-label" for="function-active">Função ativa</label></div></div></div><div class="card-footer bg-white text-end"><button class="btn btn-primary" [disabled]="form.invalid||saving()">{{saving()?'Salvando…':'Salvar função'}}</button></div></form>@if(error()){<div class="alert alert-danger mt-3">{{error()}}</div>}
`})
export class FunctionForm{private readonly fb=inject(FormBuilder);private readonly api=inject(SectorService);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);readonly id=Number(this.route.snapshot.paramMap.get('id'))||0;readonly saving=signal(false);readonly error=signal('');readonly form=this.fb.nonNullable.group({name:['',Validators.required],code:['',Validators.required],description:[''],active:[true]});constructor(){if(this.id)this.api.getFunction(this.id).subscribe({next:item=>this.form.patchValue(item),error:()=>this.error.set('Não foi possível carregar a função.')});}submit(){this.form.markAllAsTouched();if(this.form.invalid||this.saving())return;const v=this.form.getRawValue(),payload={name:v.name.trim(),code:v.code.trim(),description:v.description.trim(),active:v.active};this.saving.set(true);this.error.set('');(this.id?this.api.updateFunction(this.id,payload):this.api.createFunction(payload)).pipe(finalize(()=>this.saving.set(false))).subscribe({next:()=>this.router.navigateByUrl('/administracao/estrutura/funcoes'),error:r=>this.error.set(this.first(r.error)||'Não foi possível salvar a função.')});}private first(error:unknown){if(!error||typeof error!=='object')return'';const v=Object.values(error as Record<string,unknown>)[0];return Array.isArray(v)?String(v[0]):String(v||'');}}
